name: Android Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.0'
          additional-tools: 'platform-tools cmdline-tools'

      # Grant execute permissions to gradlew
      - name: Grant execute permissions
        run: chmod +x ./gradlew

      # Run Lint check (Debug & Release)
      - name: Run Lint Check
        run: ./gradlew lintDebug lintRelease --continue

      # Debug: List all Lint reports to find the correct path
      - name: List Lint Reports
        run: ls -R app/build/reports/lint/

      # Upload Lint Report as an artifact
      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html  # Adjusted path